# Pandas in Python

In [1]:
# Def: Pandas is a open source library designed to perform data manipulation and Analysis.

# Pandas is built over the Numpy.

# Pandas datastructure like DataFrame will store the data at backend using Numpy 2D array.

# Important list of operations in Pandas
1. Installation of Pandas
2. Data structure (Series, Data Frame)
3. Input and Output data in pandas (CSV, EXCEL, SQL, JSON)
4. Understanding the dataset (head, tail, dtype..)
5. Data filtering and indexing (loc, iloc, where()..)
6. Handling of Null values (NaN, NULL)
7. Remove duplicates
8. Handling of inconsistency inside the data (RAJ, Raj, raj, RAj, Mr.Raj, Mr. Raj)
9. Data transformation using apply(), map()
10. Aggregation and Grouping
11. Time Series operation
12. Data Visualization

# 1. Installation of Pandas

In [1]:
# pip install pandas
# conda install pandas

# this command will install the NEW version of pandas but other dependent libraries still support 
# old version of panda so they will create the issue

import pandas as pd

In [3]:
pd.__version__

'2.2.3'

# 2. Data structure (Series, Data Frame)

In [4]:
# Series : 1D array

ser1 = pd.Series()

print(ser1)

Series([], dtype: object)

In [5]:
# create a series from list

Salary = [50, 25, 75, 15, 32, 90, 100, 200, 300, 500]

Salary_series = pd.Series(Salary)
print(Salary_series)

0     50
1     25
2     75
3     15
4     32
5     90
6    100
7    200
8    300
9    500
dtype: int64

In [6]:
type(Salary_series)

pandas.core.series.Series

In [10]:
# Series() don't support the Negative indexing
Salary_series[-1]

KeyError: -1

In [12]:
# Series from the Tuple

X_names = ("Chinki", "Minki", "Tinki", "Pinki")

Salary_series = pd.Series(X_names, index = ['A', 'B', 'C', 'D'])
print(Salary_series)

A    Chinki
B     Minki
C     Tinki
D     Pinki
dtype: object

In [13]:
Salary_series['B']

'Minki'

## Data frame in pandas

In [14]:
# dataframe is 2D array / Tables

df1 = pd.DataFrame()

print(df1)

Empty DataFrame
Columns: []
Index: []

In [20]:
# creating df from list
fruits = ["Arati Pandu", "Mamidi Pandu", "Kamala Pandu", "Panasa pandu"]

df1 = pd.DataFrame(fruits, columns = ['Pandu Peru'])

print(df1)

     Pandu Peru
0   Arati Pandu
1  Mamidi Pandu
2  Kamala Pandu
3  Panasa pandu

In [16]:
type(df1)

pandas.core.frame.DataFrame

In [23]:
# list of list into dataframe
fruits = [["Arati Pandu",70], ["Mamidi Pandu",800], ["Kamala Pandu", 300], ["Panasa pandu",120]]

df1 = pd.DataFrame(fruits, columns = ["Pandu Peru", "Darah"])
print(df1)

     Pandu Peru  Darah
0   Arati Pandu     70
1  Mamidi Pandu    800
2  Kamala Pandu    300
3  Panasa pandu    120

In [26]:
# tuple of tuple into dataframe
fruits = {("Arati Pandu",70), ("Mamidi Pandu",800), ("Kamala Pandu", 300), ("Panasa pandu",120)}

df1 = pd.DataFrame(fruits, columns = ["Pandu Peru", "Darah"])
print(df1)

     Pandu Peru  Darah
0  Kamala Pandu    300
1  Panasa pandu    120
2  Mamidi Pandu    800
3   Arati Pandu     70

In [36]:
# Creating a Dataframe from the Dictionary

South_Hero = {
    "Hero Name" : ["NTR", "Prabhas", "Anudeep", "BoB", "PK", "Kirti Suresh"],
    "Movie Fee" : [200, 1000, 0, 500, 50, 100]    
}

df1 = pd.DataFrame(South_Hero)
print(df1)

      Hero Name  Movie Fee
0           NTR        200
1       Prabhas       1000
2       Anudeep          0
3           BoB        500
4            PK         50
5  Kirti Suresh        100

# 3. Input and Output data in pandas (CSV, EXCEL, SQL, JSON)

In [37]:
# Load the CSV file to DataFrame

import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [3]:
df_csv = pd.read_csv("CSV_data.csv")

In [4]:
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [5]:
# Load the Excel file as Data Frame
df = pd.read_excel("Excel_data.xlsx")
type(df)

pandas.core.frame.DataFrame

In [6]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [7]:
import pandas as pd

In [8]:
# Store the dataframe (df) into CSV & Excel file
df.to_excel("Da19_Excel_file123.xlsx", index = False)